artifact_uri: ../mlflow/1/da0d56d4b3d6439b9bf7961ded05ecb0/artifacts
end_time: 1601223925191
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: da0d56d4b3d6439b9bf7961ded05ecb0
run_uuid: da0d56d4b3d6439b9bf7961ded05ecb0
source_name: ''
source_type: 4
source_version: ''
start_time: 1601223740997
status: 3
tags: []
user_id: root
