artifact_uri: ../mlflow/0/13e8e5efeb504ada821a6a064a73a8c5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 13e8e5efeb504ada821a6a064a73a8c5
run_uuid: 13e8e5efeb504ada821a6a064a73a8c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1601223110789
status: 1
tags: []
user_id: root
