artifact_uri: ../mlflow/1/2efdaa7a2176477d8ff331040d5afc7f/artifacts
end_time: 1601223374359
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2efdaa7a2176477d8ff331040d5afc7f
run_uuid: 2efdaa7a2176477d8ff331040d5afc7f
source_name: ''
source_type: 4
source_version: ''
start_time: 1601223190783
status: 3
tags: []
user_id: root
